apiVersion: v1
kind: ConfigMap
metadata:
  name: price-game-config
  namespace: dev-live
data:
  react.app.datasource.merchant.link: https://shop-data.dev-live.full.tanzu-play-caa.net/merchant
  react.app.datasource.players.link: https://shop-data.dev-live.full.tanzu-play-caa.net/players
