version: '1'
services:
  game:
    container_name: game
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: always
  players:
    container_name: players
    build: 
      context: .
      dockerfile: Dockerfile.players
    ports:
      - "3030:3000"
    restart: always
  merchant:
    container_name: merchant
    build: 
      context: .
      dockerfile: Dockerfile.merchant
    ports:
      - "3031:3000"
    restart: always