version: '3'

services:
  price-game:
    image: pkhamdee/price-game:1.3
    container_name: price-game
    ports:
      - "80:80"
    restart: always
    links:
     - shop-data
    environment:
     - REACT_APP_DATASOURCE_PLAYERS_LINK=http://localhost:3030/players
     - REACT_APP_DATASOURCE_MERCHANT_LINK=http://localhost:3030/merchant
  shop-data:
    container_name: shop-data
    image: pkhamdee/shop-api:1.2
    env_file:
      - env.shop-data
    ports:
      - "3030:3000"
    restart: always    
    links:
      - db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_DB: shop_data
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql    
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  db: 
    driver: local     
