apiVersion: v1
kind: ConfigMap
metadata:
  name: price-game-config
  namespace: dev-live
data:
  app.name: shop-data
  app.service.name: backend
  otel.collector.url: http://localhost:4318/v1/traces
  otel.enable: "false"
  datasource.merchant.link: https://shop-data-dev-live.tap-iterate.tanzu-play-caa.net/merchant
  datasource.players.link: https://shop-data-dev-live.tap-iterate.tanzu-play-caa.net/players
