apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: price-game
  namespace: dev-live
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: price-game
spec:
  env:
  - name: REACT_APP_DATASOURCE_PLAYERS_LINK
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: datasource.players.link
  - name: REACT_APP_DATASOURCE_MERCHANT_LINK
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: datasource.merchant.link
  - name: REACT_APP_APP_NAME
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: app.name
  - name: REACT_APP_APP_SERVICE_NAME
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: app.service.name
  - name: REACT_APP_OTEL_COLLECTOR_URL
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: otel.collector.url
  - name: REACT_APP_OTEL_ENABLE
    valueFrom:
      configMapKeyRef:
        name: price-game-config
        key: otel.enable
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: clusterBuilder
      value: full-jammy
    - name: buildServiceBindings
      value:
      - kind: Secret
        name: npmrc
  build:
    env:
      - name: BP_NODE_RUN_SCRIPTS
        value: "build"
  source:
    git:
      url: https://github.com/pkhamdee/balloon-popping-game
      ref:
        branch: main
